"""Textes du formulaire d'arrivée et des emails — français (référence) et anglais."""

T = {
"fr": {
    "title": "Formulaire d'arrivée",
    "welcome_title": "Bienvenue !",
    "welcome_body": "<p>Merci d'avoir choisi <strong>La Villa des Sables du Lagon</strong> pour votre séjour. Nous espérons que vous y passerez de merveilleux moments.</p>"
                    "<p class='mb-1'>Ce formulaire a deux objectifs :</p><ol class='mb-2'><li>répondre à nos obligations légales de loueur ;</li>"
                    "<li>confirmer ensemble quelques règles clés de la villa, pour que votre séjour corresponde à vos attentes.</li></ol>"
                    "<p class='hint mb-0'>Il vous prendra deux ou trois minutes.</p>",
    "welcome_res": "Réservation {ref} · arrivée le {arrival}, départ le {departure} · {guests} personnes",
    "booking_lbl": "Réservation", "arrival_lbl": "Arrivée", "departure_lbl": "Départ", "guests_lbl": "Voyageurs",
    "start": "C'est parti !",
    "next": "Suivant", "prev": "Retour", "submit": "Signer et envoyer",
    "step_rules": "Règles", "step_identity": "Identité", "step_id": "Pièce d'identité", "step_consents": "Consentements", "step_sign": "Signature",
    "rules_title": "Les règles de la villa",
    "rules_intro_platform": "Ces règles figurent sur {listing}. Merci de confirmer, une par une, que vous en avez pris connaissance, que vous les acceptez et que vous vous engagez à les respecter et à les faire respecter par tous les occupants.",
    "rules_intro_direct": "Ces règles font partie de nos conditions de location. Merci de confirmer, une par une, que vous en avez pris connaissance, que vous les acceptez et que vous vous engagez à les respecter et à les faire respecter par tous les occupants.",
    "listing_airbnb": "notre annonce Airbnb", "listing_booking": "notre annonce Booking.com", "listing_abritel": "notre annonce Abritel", "listing_lodgify": "nos conditions de location",
    "yes": "Oui, je m'engage", "no": "Non",
    "rule_no_hint": "Si cette règle ne vous convient pas, vous pourrez demander l'annulation de la réservation à l'étape suivante.",
    "refuse_title": "Vous n'acceptez pas certaines règles",
    "refuse_body": "Vous avez répondu « Non » à : {rules}. Pas de panique : vous pouvez revoir vos réponses, ou nous signaler que ces règles ne vous conviennent pas — nous vous recontacterons pour annuler la réservation et vous rembourser les sommes versées, conformément à nos conditions.",
    "refuse_review": "Revoir mes réponses", "refuse_send": "Ces règles ne me conviennent pas, demander l'annulation",
    "refused_done_title": "Demande transmise",
    "refused_done_body": "Nous avons bien noté que les règles ne vous conviennent pas. Nous vous recontactons rapidement au sujet de l'annulation de votre réservation.",
    "identity_title": "Vos coordonnées",
    "identity_intro": "Renseignez les informations telles qu'elles figurent sur votre pièce d'identité (locataire principal, majeur).",
    "full_name": "Nom et prénom(s)", "birth_date": "Date de naissance", "birth_place": "Lieu de naissance", "nationality": "Nationalité",
    "street": "Adresse (rue)", "postal_code": "Code postal", "city": "Ville", "country": "Pays",
    "email": "Email", "phone": "Téléphone portable (avec indicatif, ex. +33 6…)",
    "arrival_time": "Heure d'arrivée prévue", "arrival_time_unknown": "Je ne sais pas encore",
    "occupants": "Nombre total d'occupants (12 maximum)", "occupants_list": "Autres occupants (nom et âge, un par ligne — facultatif)",
    "adult_error": "Le locataire principal doit être majeur (18 ans révolus).", "optional": "facultatif",
    "email_error": "Adresse email invalide.", "invalid_value": "Valeur invalide.",
    "id_title": "Pièce d'identité",
    "id_intro": "Merci de joindre une pièce d'identité en cours de validité du locataire principal (carte d'identité recto/verso ou passeport) : photo ou PDF, 3 fichiers maximum. Elle est conservée de façon sécurisée et supprimée automatiquement après le séjour.",
    "id_files": "Fichiers", "id_take": "Prendre une photo ou choisir un fichier",
    "consents_title": "Engagements et consentements",
    "erp_label": "Je confirme que je prendrai connaissance de l'état des risques qui me sera envoyé par email avant mon arrivée.",
    "erp_hint": "Conformément à l'article L.125-5 du Code de l'environnement (loi ELAN n° 2018-1021), l'état des risques et pollutions obligatoire vous est transmis automatiquement par email avant votre séjour.",
    "marketing_title": "Souhaitez-vous être informé(e) des nouveautés et des offres promotionnelles (ex. tarifs réduits) émanant exclusivement de la Villa des Sables du Lagon ?",
    "marketing_hint": "Vos coordonnées ne sont jamais transmises à des tiers.",
    "mkt_email": "Email pour la newsletter", "mkt_phone": "Portable pour les offres par SMS",
    "rgpd_label": "Je confirme avoir pris connaissance des dispositions relatives à la protection de mes données (RGPD).",
    "rgpd_text": "Les informations recueillies sur ce formulaire sont enregistrées dans un fichier informatisé par SCI LES SABLES DU LAGON, RCS Saint-Denis de La Réunion 821 948 163, pour (i) la validation des conditions de location, (ii) l'envoi de la documentation obligatoire et (iii) le cas échéant l'envoi d'informations et d'offres promotionnelles. Les bases légales du traitement sont le consentement, le contrat, l'obligation légale et l'intérêt légitime. Les données sont hébergées dans l'Union européenne (outil Vaelan, serveurs Render à Francfort) et ne sont transmises à aucun autre destinataire. Elles sont conservées cinq (5) ans ; les copies de pièces d'identité sont supprimées automatiquement six mois après le séjour. Vous pouvez accéder à vos données, les rectifier, demander leur effacement ou la limitation de leur traitement, et retirer votre consentement à tout moment : {rgpd_email} ou par courrier à SCI LES SABLES DU LAGON, 6 ruelle Mazeau, 97400 Saint-Denis. Vous pouvez introduire une réclamation auprès de la CNIL (cnil.fr).",
    "sign_title": "Il ne manque plus que votre signature !",
    "sign_intro": "Signez avec le doigt (ou la souris) dans le cadre ci-dessous. En signant, vous confirmez l'exactitude des informations fournies et votre engagement à respecter les règles de la villa.",
    "sign_clear": "Effacer", "sign_missing": "Merci de signer dans le cadre.",
    "sign_legal": "Signature électronique horodatée, avec adresse IP, valant acceptation des conditions.",
    "done_title": "Merci !",
    "done_body": "Nous avons bien reçu votre formulaire. Un récapitulatif signé vient de vous être envoyé par email{email}. Nous avons hâte de vous accueillir à la Villa des Sables du Lagon et vous souhaitons de créer de très beaux souvenirs pendant votre séjour. D'ici là, n'hésitez pas à nous contacter pour toute question. Salutations ensoleillées !",
    "already_title": "Formulaire déjà rempli",
    "already_body": "Ce formulaire a déjà été rempli et signé le {date}. Si vous devez modifier une information, contactez-nous.",
    "invalid_title": "Lien invalide",
    "invalid_body": "Ce lien ne correspond à aucune réservation en cours. Vérifiez le lien reçu ou contactez-nous.",
    "required": "Champ obligatoire", "file_too_big": "Fichier trop volumineux (max {mb} Mo)", "file_type": "Format accepté : photo (JPG, PNG, HEIC) ou PDF",
    "lang_switch": "English version",
    # emails voyageur
    "mail_invite_subject": "La Villa des Sables du Lagon — formulaire d'arrivée à compléter (réservation {ref})",
    "mail_invite_body": "Bonjour {name},\n\nNous vous remercions d'avoir choisi La Villa des Sables du Lagon pour votre séjour du {arrival} au {departure} et nous nous réjouissons de vous accueillir.\n\nAfin de préparer votre arrivée et de répondre à nos obligations de loueur, nous vous invitons à compléter notre formulaire d'arrivée. Il ne prend que 2 à 3 minutes et permet de confirmer ensemble les quelques règles de vie de la villa :\n\n{url}\n\nNous restons à votre disposition pour toute question.\n\nBien cordialement,\nLa Villa des Sables du Lagon",
    "mail_remind_subject": "Rappel — formulaire d'arrivée La Villa des Sables du Lagon (réservation {ref})",
    "mail_remind_body": "Bonjour {name},\n\nPetit rappel : votre formulaire d'arrivée pour votre séjour du {arrival} au {departure} n'est pas encore complété. Il ne prend que 2 à 3 minutes et nous permet de préparer votre accueil :\n\n{url}\n\nMerci d'avance et à très bientôt,\nLa Villa des Sables du Lagon",
    "mail_confirm_subject": "La Villa des Sables du Lagon — votre formulaire d'arrivée signé (réservation {ref})",
    "mail_confirm_body": "Bonjour {name},\n\nNous avons bien reçu votre formulaire d'arrivée signé le {date}. Vous trouverez en pièce jointe le récapitulatif signé de vos réponses et des règles acceptées : {file}\n\nRappel des horaires : arrivée {checkin}, départ {checkout}.\n\nÀ très bientôt à la Villa des Sables du Lagon !",
    "mail_erp_subject": "La Villa des Sables du Lagon — état des risques (réservation {ref})",
    "mail_erp_body": "Bonjour {name},\n\nComme convenu dans votre formulaire d'arrivée, vous trouverez en pièce jointe l'état des risques et pollutions relatif à la villa (article L.125-5 du Code de l'environnement).\n\nNous vous souhaitons un excellent séjour,\nLa Villa des Sables du Lagon",
    "sms_invite": "Bonjour {name}, merci d'avoir choisi La Villa des Sables du Lagon pour votre séjour du {arrival} au {departure} ! Nous nous réjouissons de vous accueillir.\n\nPour préparer votre arrivée et répondre à nos obligations de loueur, pourriez-vous compléter notre formulaire d'arrivée ? Il ne prend que 2 à 3 minutes et permet de confirmer ensemble les quelques règles de vie de la villa :\n\n{url}\n\nMerci d'avance et à très bientôt,\nLa Villa des Sables du Lagon",
    "sms_remind": "Bonjour {name}, petit rappel : votre formulaire d'arrivée pour votre séjour du {arrival} au {departure} n'est pas encore complété. Il ne prend que 2 à 3 minutes et nous permet de préparer votre accueil :\n\n{url}\n\nMerci d'avance et à très bientôt,\nLa Villa des Sables du Lagon",
    "nolink_invite": "Bonjour {name}, merci d'avoir choisi La Villa des Sables du Lagon pour votre séjour du {arrival} au {departure} ! Nous nous réjouissons de vous accueillir.\n\nPour préparer votre arrivée et répondre à nos obligations de loueur, nous vous demandons de compléter un court formulaire d'arrivée (2 à 3 minutes), qui permet aussi de confirmer ensemble les quelques règles de vie de la villa.\n\nLes liens ne passant pas dans cette messagerie, nous vous l'envoyons par SMS ou WhatsApp au numéro de votre réservation{phone}. Si vous préférez un autre numéro ou une adresse email, indiquez-le-nous ici.\n\nMerci d'avance et à très bientôt,\nLa Villa des Sables du Lagon",
    "nolink_remind": "Bonjour {name}, petit rappel : votre formulaire d'arrivée pour votre séjour du {arrival} au {departure} n'est pas encore complété (2 à 3 minutes).\n\nLe lien vous a été envoyé par SMS ou WhatsApp{phone} ; dites-nous si vous ne l'avez pas reçu ou si vous préférez un autre numéro ou une adresse email.\n\nMerci d'avance et à très bientôt,\nLa Villa des Sables du Lagon",
},
"en": {
    "title": "Arrival form",
    "welcome_title": "Welcome!",
    "welcome_body": "<p>Thank you for choosing <strong>La Villa des Sables du Lagon</strong> for your stay. We hope you will have wonderful moments here.</p>"
                    "<p class='mb-1'>This form has two purposes:</p><ol class='mb-2'><li>to meet our legal obligations as a landlord;</li>"
                    "<li>to confirm together a few key rules of the villa, so that your stay matches your expectations.</li></ol>"
                    "<p class='hint mb-0'>It will take two or three minutes.</p>",
    "welcome_res": "Booking {ref} · arrival {arrival}, departure {departure} · {guests} guests",
    "booking_lbl": "Booking", "arrival_lbl": "Arrival", "departure_lbl": "Departure", "guests_lbl": "Guests",
    "start": "All right, let's get started!",
    "next": "Next", "prev": "Back", "submit": "Sign and send",
    "step_rules": "Rules", "step_identity": "Identity", "step_id": "ID document", "step_consents": "Consents", "step_sign": "Signature",
    "rules_title": "The rules of the villa",
    "rules_intro_platform": "These rules are stated on {listing}. Please confirm, one by one, that you have read them, that you accept them and that you commit to complying with them and ensuring all occupants do too.",
    "rules_intro_direct": "These rules are part of our rental conditions. Please confirm, one by one, that you have read them, that you accept them and that you commit to complying with them and ensuring all occupants do too.",
    "listing_airbnb": "our Airbnb listing", "listing_booking": "our Booking.com listing", "listing_abritel": "our Abritel / Vrbo listing", "listing_lodgify": "our rental conditions",
    "yes": "Yes, I commit", "no": "No",
    "rule_no_hint": "If this rule does not suit you, you will be able to request the cancellation of the booking at the next step.",
    "refuse_title": "You do not accept some rules",
    "refuse_body": "You answered “No” to: {rules}. No worries: you can review your answers, or let us know that these rules do not suit you — we will contact you to cancel the booking and refund the amounts paid, in accordance with our conditions.",
    "refuse_review": "Review my answers", "refuse_send": "These rules do not suit me, request cancellation",
    "refused_done_title": "Request received",
    "refused_done_body": "We have noted that the rules do not suit you. We will contact you shortly about the cancellation of your booking.",
    "identity_title": "Your details",
    "identity_intro": "Enter the information as it appears on your ID (main tenant, adult).",
    "full_name": "Full name", "birth_date": "Date of birth", "birth_place": "Place of birth", "nationality": "Nationality",
    "street": "Address (street)", "postal_code": "Postal code", "city": "City", "country": "Country",
    "email": "Email", "phone": "Mobile phone (with country code, e.g. +44 7…)",
    "arrival_time": "Expected arrival time", "arrival_time_unknown": "I don't know yet",
    "occupants": "Total number of occupants (12 maximum)", "occupants_list": "Other occupants (name and age, one per line — optional)",
    "adult_error": "The main tenant must be an adult (18 or over).", "optional": "optional",
    "email_error": "Invalid email address.", "invalid_value": "Invalid value.",
    "id_title": "ID document",
    "id_intro": "Please attach a valid ID document of the main tenant (ID card front/back or passport): photo or PDF, 3 files maximum. It is stored securely and deleted automatically after the stay.",
    "id_files": "Files", "id_take": "Take a photo or choose a file",
    "consents_title": "Commitments and consents",
    "erp_label": "I confirm that I will review the risk assessment sent to me by email before my arrival.",
    "erp_hint": "In accordance with Article L.125-5 of the French Environmental Code (ELAN law no. 2018-1021), the mandatory risk assessment is sent to you automatically by email before your stay.",
    "marketing_title": "Would you like to be informed about updates and promotional offers (e.g. discounted rates) exclusively from La Villa des Sables du Lagon?",
    "marketing_hint": "Your details are never shared with third parties.",
    "mkt_email": "Email for the newsletter", "mkt_phone": "Mobile for SMS offers",
    "rgpd_label": "I confirm that I am aware of the provisions regarding the protection of my data (GDPR).",
    "rgpd_text": "The information collected on this form is recorded in a computerised file by SCI LES SABLES DU LAGON, RCS Saint-Denis de La Réunion 821 948 163, for (i) validating rental terms, (ii) sending mandatory documentation and (iii) if applicable, sending information and promotional offers. The legal bases for processing are consent, contract, legal obligation and legitimate interest. Data is hosted in the European Union (Vaelan tool, Render servers in Frankfurt) and is not shared with any other recipient. It is kept for five (5) years; copies of ID documents are deleted automatically six months after the stay. You can access your data, rectify it, request its deletion or the limitation of its processing, and withdraw your consent at any time: {rgpd_email} or by post to SCI LES SABLES DU LAGON, 6 ruelle Mazeau, 97400 Saint-Denis, France. You can file a complaint with the CNIL (cnil.fr).",
    "sign_title": "Just your signature left!",
    "sign_intro": "Sign with your finger (or mouse) in the box below. By signing, you confirm the accuracy of the information provided and your commitment to comply with the rules of the villa.",
    "sign_clear": "Clear", "sign_missing": "Please sign in the box.",
    "sign_legal": "Time-stamped electronic signature, with IP address, constituting acceptance of the conditions.",
    "done_title": "Thank you!",
    "done_body": "We have received your form. A signed summary has just been sent to you by email{email}. We look forward to welcoming you to La Villa des Sables du Lagon and wish you and your loved ones beautiful memories during your stay. In the meantime, feel free to contact us with any question. Sunny greetings!",
    "already_title": "Form already completed",
    "already_body": "This form was already completed and signed on {date}. If you need to change any information, please contact us.",
    "invalid_title": "Invalid link",
    "invalid_body": "This link does not match any current booking. Please check the link you received or contact us.",
    "required": "Required field", "file_too_big": "File too large (max {mb} MB)", "file_type": "Accepted formats: photo (JPG, PNG, HEIC) or PDF",
    "lang_switch": "Version française",
    "mail_invite_subject": "La Villa des Sables du Lagon — arrival form to complete (booking {ref})",
    "mail_invite_body": "Hello {name},\n\nThank you for choosing La Villa des Sables du Lagon for your stay from {arrival} to {departure}. We look forward to welcoming you.\n\nTo prepare your arrival and meet our obligations as a landlord, we kindly ask you to complete our arrival form. It only takes 2 to 3 minutes and lets us confirm together the few house rules of the villa:\n\n{url}\n\nPlease do not hesitate to contact us with any questions.\n\nKind regards,\nLa Villa des Sables du Lagon",
    "mail_remind_subject": "Reminder — La Villa des Sables du Lagon arrival form (booking {ref})",
    "mail_remind_body": "Hello {name},\n\nA quick reminder: your arrival form for your stay from {arrival} to {departure} has not been completed yet. It only takes 2 to 3 minutes and helps us prepare your welcome:\n\n{url}\n\nThank you and see you soon,\nLa Villa des Sables du Lagon",
    "mail_confirm_subject": "La Villa des Sables du Lagon — your signed arrival form (booking {ref})",
    "mail_confirm_body": "Hello {name},\n\nWe have received your arrival form signed on {date}. Please find attached the signed summary of your answers and of the accepted rules: {file}\n\nReminder: check-in {checkin}, check-out {checkout}.\n\nSee you soon at La Villa des Sables du Lagon!",
    "mail_erp_subject": "La Villa des Sables du Lagon — risk assessment (booking {ref})",
    "mail_erp_body": "Hello {name},\n\nAs agreed in your arrival form, please find attached the risk assessment (état des risques et pollutions) for the villa (Article L.125-5 of the French Environmental Code).\n\nWe wish you a wonderful stay,\nLa Villa des Sables du Lagon",
    "sms_invite": "Hello {name}, thank you for choosing La Villa des Sables du Lagon for your stay from {arrival} to {departure}! We look forward to welcoming you.\n\nTo prepare your arrival and meet our obligations as a landlord, could you complete our arrival form? It only takes 2 to 3 minutes and lets us confirm together the few house rules of the villa:\n\n{url}\n\nThank you and see you soon,\nLa Villa des Sables du Lagon",
    "sms_remind": "Hello {name}, a quick reminder: your arrival form for your stay from {arrival} to {departure} has not been completed yet. It only takes 2 to 3 minutes and helps us prepare your welcome:\n\n{url}\n\nThank you and see you soon,\nLa Villa des Sables du Lagon",
    "nolink_invite": "Hello {name}, thank you for choosing La Villa des Sables du Lagon for your stay from {arrival} to {departure}! We look forward to welcoming you.\n\nTo prepare your arrival and meet our obligations as a landlord, we ask you to complete a short arrival form (2 to 3 minutes), which also lets us confirm together the few house rules of the villa.\n\nAs links cannot be sent through this messaging, we will send it to you by SMS or WhatsApp on the phone number of your booking{phone}. If you prefer another number or an email address, just let us know here.\n\nThank you and see you soon,\nLa Villa des Sables du Lagon",
    "nolink_remind": "Hello {name}, a quick reminder: your arrival form for your stay from {arrival} to {departure} has not been completed yet (2 to 3 minutes).\n\nThe link was sent to you by SMS or WhatsApp{phone}; let us know if you did not receive it or if you prefer another number or an email address.\n\nThank you and see you soon,\nLa Villa des Sables du Lagon",
},
}


def t(lang: str, key: str, **kw) -> str:
    d = T.get(lang) or T["fr"]
    s = d.get(key) or T["fr"].get(key) or key
    try:
        return s.format(**kw) if kw else s
    except (KeyError, IndexError):
        return s
